modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/Eruc0lind0/boom_arrow/issues" #optional

[[mods]] #mandatory
modId="boomarrow" #mandatory
version="${file.jarVersion}" #mandatory
displayName="BOOM Arrow" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/Eruc0lind0/boom_arrow" #optional
logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="Eruc0lind0" #optional
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)
description='''
This is a mod that introduces a new arrow type that explodes.

I'm almost certain nobody has ever done this before, ever, ever, ever.
'''

[[dependencies.boomarrow]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.boomarrow]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
